;/*FB_PKG_DELIM*/

__d("PluginConnectButton",["Arbiter","CSS","DOM","DOMEvent","DOMEventListener","Focus","FormSubmit","PlatformWidgetEndpoint","Plugin","PluginOptin","URI"],(function(a,b,c,d,e,f){var g,h="new",i=b("Arbiter").subscribe,j=function(a,c){return b("DOMEventListener").add(a,"click",c)};function a(a){var c=this;this.config=a;this.busy=!1;var d=b("DOM").find(a.form,".pluginConnectButton");this.buttons=d;this.node_connected=b("DOM").find(d,".pluginConnectButtonConnected");this.node_disconnected=b("DOM").find(d,".pluginConnectButtonDisconnected");var e=function(a){new(b("DOMEvent"))(a).kill(),c.busy||(c.submit(),c.busy=c.canpersonalize)};j(this.node_disconnected,e);a.buttontype===1?j(b("DOM").find(d,".pluginButtonX button"),e):a.buttontype===2&&j(this.node_connected,e);j(this.node_connected,function(a){return b("Arbiter").inform(b("Plugin").DIALOG,a)});d=this.update.bind(this);i(b("Plugin").CONNECT,d,h);i(b("Plugin").DISCONNECT,d,h);i(b("Plugin").ERROR,this.error.bind(this),h)}Object.assign(a.prototype,{update:function(a,c){this.busy=!1;var d=this.config;if(c.identifier!==d.identifier)return;c=a===b("Plugin").CONNECT;a=b("PlatformWidgetEndpoint").plugins(d.plugin);a+="/"+(c?"disconnect":"connect");b("CSS")[c?"show":"hide"](this.node_connected);b("CSS")[c?"hide":"show"](this.node_disconnected);try{if(document.activeElement.nodeName.toLowerCase()==="button"){var e=c?this.node_connected:this.node_disconnected;e=b("DOM").find(e,"button");e.disabled=!1;b("Focus").set(e)}}catch(a){}d.connected=c;d.form.setAttribute("action",a);d.form.setAttribute("ajaxify",a)},error:function(a,c){this.busy=!1;if(c.action in{connect:1,disconnect:1}){b("DOM").setContent(this.buttons,c.content);a=b("DOM").scry(this.buttons,".confirmButton");a.length===1&&b("Focus").set(a[0])}},submit:function(){if(!this.config.canpersonalize)return this.login();b("FormSubmit").send(this.config.form);this.fireStateToggle()},fireStateToggle:function(){var a=this.config;a.connected?b("Plugin").disconnect(a.identifier):b("Plugin").connect(a.identifier)},login:function(){var a=this.config.plugin;new(b("PluginOptin"))(a,(g||(g=b("URI"))).getRequestURI().getQueryData().api_key).addReturnParams({act:"connect"}).addLoginParams({social_plugin_action:this.config.pluginaction,kid_directed_site:this.config.kidDirectedSite}).start()}});e.exports=a}),null);
__d("ImmutableServerCallableWrapper",["immutable"],(function(a,b,c,d,e,f,g){"use strict";g["default"]=c("immutable")}),98);
__d("isEmail",[],(function(a,b,c,d,e,f){var g=/^[\w!#\$%&\'\*\+\/\=\?\^`\{\|\}~\-]+(:?\.[\w!#\$%&\'\*\+\/\=\?\^`\{\|\}~\-]+)*@(?:[a-z0-9](?:[a-z0-9\-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9\-]*[a-z0-9])?$/i;function a(a){return g.test(a)}f["default"]=a}),66);
__d("IntlCLDRNumberType06",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a===0||a===1)return c("IntlVariations").NUMBER_ONE;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType07",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a>=0&&a<=1)return c("IntlVariations").NUMBER_ONE;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType08",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a>=0&&a<=1||a>=11&&a<=99)return c("IntlVariations").NUMBER_ONE;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType11",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a%10===1&&a%100!==11)return c("IntlVariations").NUMBER_ONE;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType12",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a%10===1&&a%100!==11)return c("IntlVariations").NUMBER_ONE;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType13",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a===1||a===2||a===3||a%10!==4&&a%10!==6&&a%10!==9)return c("IntlVariations").NUMBER_ONE;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType27",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a%10===1&&a%100!==11)return c("IntlVariations").NUMBER_ONE;else if(a%10>=2&&a%10<=4&&(a%100<12||a%100>14))return c("IntlVariations").NUMBER_FEW;else return c("IntlVariations").NUMBER_MANY}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType29",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a===1)return c("IntlVariations").NUMBER_ONE;else if(a===0||a%100>=2&&a%100<=10)return c("IntlVariations").NUMBER_FEW;else if(a%100>=11&&a%100<=19)return c("IntlVariations").NUMBER_MANY;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType32",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a===1)return c("IntlVariations").NUMBER_ONE;else if(a===2)return c("IntlVariations").NUMBER_TWO;else if(a>=3&&a<=6)return c("IntlVariations").NUMBER_FEW;else if(a>=7&&a<=10)return c("IntlVariations").NUMBER_MANY;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType35",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a===0)return c("IntlVariations").NUMBER_ZERO;else if(a===1)return c("IntlVariations").NUMBER_ONE;else if(a===2)return c("IntlVariations").NUMBER_TWO;else if(a===3)return c("IntlVariations").NUMBER_FEW;else if(a===6)return c("IntlVariations").NUMBER_MANY;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType36",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a===0||a===1)return c("IntlVariations").NUMBER_ONE;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType37",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a===1)return c("IntlVariations").NUMBER_ONE;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType38",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a===0||a===1)return c("IntlVariations").NUMBER_ONE;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType43",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a===1)return c("IntlVariations").NUMBER_ONE;else if(a%10>=2&&a%10<=4&&(a%100<12||a%100>14))return c("IntlVariations").NUMBER_FEW;else return c("IntlVariations").NUMBER_MANY}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType44",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a>=0&&a<=1)return c("IntlVariations").NUMBER_ONE;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("IntlCLDRNumberType45",["IntlVariations"],(function(a,b,c,d,e,f,g){"use strict";a={getVariation:function(a){if(a===1)return c("IntlVariations").NUMBER_ONE;else if(a===2)return c("IntlVariations").NUMBER_TWO;else return c("IntlVariations").NUMBER_OTHER}};b=a;g["default"]=b}),98);
__d("PluginConnectSendToMessengerWebhook",["goURI"],(function(a,b,c,d,e,f,g){"use strict";function a(a){c("goURI")(a)}g.redirectToNext=a}),98);
__d("PlatformWindowDialogCloser",[],(function(a,b,c,d,e,f){"use strict";function a(){window.close()}f.close=a}),66);
__d("PluginOptinResurrectCookie",["EventListener","goURI"],(function(a,b,c,d,e,f,g){"use strict";function a(a){var b=!1;c("EventListener").listen(document,"click",function(){b||(b=!0,c("goURI")(a))})}g.init=a}),98);
__d("normalizeDeltaYaw",[],(function(a,b,c,d,e,f){"use strict";function a(a,b){b=b?Math.PI:180;var c=2*b;if(Math.abs(a)>c){var d=Math.trunc(Math.abs(a)/c);a-=Math.sign(a)*d*c}Math.abs(a)>b&&(a-=Math.sign(a)*2*b);return a}f["default"]=a}),66);
__d("filterNulls",[],(function(a,b,c,d,e,f){"use strict";function a(a){var b=[];for(var a=a,c=Array.isArray(a),d=0,a=c?a:a[typeof Symbol==="function"?Symbol.iterator:"@@iterator"]();;){var e;if(c){if(d>=a.length)break;e=a[d++]}else{d=a.next();if(d.done)break;e=d.value}e=e;e!=null&&b.push(e)}return b}f["default"]=a}),66);